### ISSUE TITLE
chmod: changing permissions of '/data': Operation not permitted

### ISSUE THREAD

**Issue by trungdlp-wolffun** [gilesknap/k3s-minecraft#4]
chmod: changing permissions of '/data': Operation not permitted
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 2 0 0 4096 Feb  7 14:30 /data'
[init] Resolved version given 1.19.3 into 1.19.3 and major version 1.19
[init] Resolving type given VANILLA
[init] Downloading 1.19.3 server...

**Comment by gilesknap** [comment]
I believe that is a benign error. Is it causing you issues?
