### ISSUE TITLE
Pod stuck in CrashLoopbackoff state

### ISSUE THREAD

**Issue by Tomoyukiryu** [gilesknap/k3s-minecraft#5]
As I stated above pod is stuck.
Env:
k3s version : 1.20.15
nodes:
 2 raspberry pi 4

My config:
[here](https://pastebin.com/6439v92B)

**Comment by gilesknap** [comment]
Hey @Tomoyukiryu.

To diagnose this could you try a couple of things and post the results please?

- kubectl get deployments -n minecraft
  -  you should see your deployment you made
- kubectl describe -n minecraft deployments/<your deployment name>
- then also see if you can get the same for the pod
  - kubectl get deployments -n pods
  - kubectl describe -n minecraft pods/<your pod name>

**Comment by gilesknap** [comment]
You config pastebin does not seem to be there - maybe it timed out? If you could just paste the yaml file you made into this issue I could probably help using that.

**Comment by Tomoyukiryu** [comment]
I didn't set any time out and when I open it on another device it works,but here is the config:
`minecraftServer:
  version: 1.12.2
  whitelist:
  eula: true
  ops: [REDACTED]
  levelSeed:
  gameMode: survival
  motd: "Welcome to Minecraft on Kubernetes"
  pvp: true
  serviceType: NodePort
  nodePort: 30100
  viewDistance: 10
  type: "AUTO_CURSEFORGE"
  difficulty: normal
  forcegameMode: true
  memory: 2g
  autoCurseForge:
    slug: multiblock-madness
    apiKey: 
     key: "[REDACTED]"
persistence:
  annotations: {}
  dataDir:
    enabled: true
    Size: 10Gi
resources:
  requests:
    memory: 2Gi
    cpu: 1
  limits:
    memory: 3Gi
    cpu: 6Gi
 
 `

**Comment by gilesknap** [comment]
I'm not sure I can help with this. You might get better luck posting your issue to https://github.com/itzg/docker-minecraft-server

**Comment by Tomoyukiryu** [comment]
Thank you for your help anyway
